name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "rwwr.wang"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.rwwr.wang", custom_domain = true },
  { pattern = "quay.rwwr.wang", custom_domain = true },
  { pattern = "gcr.rwwr.wang", custom_domain = true },
  { pattern = "k8s-gcr.rwwr.wang", custom_domain = true },
  { pattern = "k8s.rwwr.wang", custom_domain = true },
  { pattern = "ghcr.rwwr.wang", custom_domain = true },
  { pattern = "cloudsmith.rwwr.wang", custom_domain = true },
  { pattern = "docker-staging.rwwr.wang", custom_domain = true },
  { pattern = "hello-world.rwwr.wang", custom_domain = true }  # 这里新增 hello-world 的代理配置
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.rwwr.wang", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = "https://registry-1.docker.io"
